In [1]:
import pandas as pd
import numpy as np

#enough for our cleaning purposes

In [2]:
df = pd.read_csv(r"E:\MLOps\MMT\Data\Raw\marketing_sample_for_makemytrip_com-travel__20190901_20190930__30k_data.csv", on_bad_lines = "skip")

In [3]:
df.columns

Index(['Uniq Id', 'Crawl Timestamp', 'Package Name', 'Page Url',
       'Package Type', 'Company', 'Destination', 'Itinerary', 'Places Covered',
       'Travel Date', 'Hotel Details', 'Start City', 'Airline', 'Flight Stops',
       'Onwards Return Flight Time', 'Meals', 'Price Per Two Persons',
       'Per Person Price', 'Sightseeing Places Covered',
       'Initial Payment For Booking', 'Cancellation Rules',
       'Date Change Rules'],
      dtype='object')

In [4]:
df.drop(columns = [ 
    "Flight Stops", 
    "Meals",
    "Initial Payment For Booking",
    "Date Change Rules", "Crawl Timestamp",
    "Uniq Id", "Page Url"
],inplace = True)

In [6]:
df.drop(columns = [ 
   "Crawl Timestamp",
],inplace = True)

KeyError: "['Crawl Timestamp'] not found in axis"

In [ ]:
df.drop(columns = [ 
   "Cancellation Rules",
],inplace = True)

In [ ]:
df.drop("Onwards Return Flight Time", axis=1, inplace=True)

In [ ]:
df.drop("Price Per Two Persons", axis=1, inplace=True)

In [ ]:
df.drop("Company", axis=1, inplace=True)

In [ ]:
df.shape

(27454, 12)

In [ ]:
df.isnull().sum()

Package Name                     0
Package Type                     0
Destination                      0
Itinerary                        0
Places Covered                   0
Travel Date                      0
Hotel Details                 4167
Start City                       0
Airline                          0
Per Person Price                 0
Sightseeing Places Covered    2127
Cancellation Rules            1138
dtype: int64

In [ ]:
df[df["Hotel Details"].isnull()][["Hotel Details", "Per Person Price"]].head(10)

   Hotel Details  Per Person Price
2            NaN            6022.5
4            NaN           17862.5
17           NaN            4782.5
20           NaN            8850.0
27           NaN           74352.5
38           NaN            7043.0
42           NaN           10497.0
54           NaN           22398.5
57           NaN            3742.0
59           NaN           17594.0

In [ ]:
df[df["Airline"].isnull()][["Airline", "Package Type", "Destination", "Per Person Price"]].head(10)

,Airline,Package Type,Destination,Per Person Price
2,NaN,Deluxe,Manali,6022.5
4,NaN,Standard,Shimla|Manali|Dharamshala|Dalhousie|Chandigarh,17862.5
8,NaN,Deluxe,Dharamshala,6713.5
17,NaN,Standard,Nainital,4782.5
20,NaN,Luxury,Manali|Chandigarh,8850.0
23,NaN,Luxury,Goa,8384.5
25,NaN,Deluxe,Dalhousie,7271.0
26,NaN,Deluxe,Colombo|Kandy|Bentota,13471.5
27,NaN,Luxury,New Delhi|Agra|Ranthambhore|Jaipur,74352.5
37,NaN,Premium,Dharamshala|Dalhousie,8138.5

In [ ]:
df["Airline"].fillna("Not Available", inplace=True)

C:\Users\Aamir\AppData\Local\Temp\ipykernel_2152\3532556588.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Airline"].fillna("Not Available", inplace=True)

In [ ]:
df["Airline"].isnull().sum()

np.int64(0)

In [ ]:
df[df["Sightseeing Places Covered"].isnull()][
    ["Sightseeing Places Covered", "Destination", "Per Person Price"]
].head(10)

,Sightseeing Places Covered,Destination,Per Person Price
12,NaN,Goa,18756.0
14,NaN,Makemytrip,36007.5
60,NaN,Nainital,13893.0
88,NaN,Kasauli,5813.5
96,NaN,Goa,10544.5
97,NaN,Ooty|Mysore,10681.0
103,NaN,Dubai,17450.5
104,NaN,Kandy|Nuwara Eliya|Bentota|Colombo,25304.0
131,NaN,Gangtok|Darjeeling,17729.0
142,NaN,Goa,9598.0

In [ ]:
df["Sightseeing Places Covered"].fillna("Not Available", inplace=True)

C:\Users\Aamir\AppData\Local\Temp\ipykernel_2152\1465454519.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Sightseeing Places Covered"].fillna("Not Available", inplace=True)

In [ ]:
df[df["Cancellation Rules"].isnull()][
    ["Cancellation Rules", "Package Type", "Destination", "Per Person Price"]
].head(10)

    Cancellation Rules Package Type              Destination  Per Person Price
42                 NaN     Standard  Shimla|Manali|New Delhi           10497.0
60                 NaN      Premium                 Nainital           13893.0
67                 NaN      Premium  Munnar|Thekkady|Allepey           17782.0
80                 NaN     Standard               Kodaikanal            6146.0
131                NaN     Standard       Gangtok|Darjeeling           17729.0
134                NaN       Luxury                   Shimla           21305.5
189                NaN     Standard    Kandy|Bentota|Colombo           19095.0
192                NaN      Premium        Shimla|Chandigarh           21460.0
200                NaN       Deluxe            Shimla|Manali           12076.5
218                NaN       Deluxe   Shimla|Manali|Amritsar           14500.0

In [ ]:
df["Cancellation Rules"].fillna("Not Available", inplace=True)

C:\Users\Aamir\AppData\Local\Temp\ipykernel_2152\350833551.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Cancellation Rules"].fillna("Not Available", inplace=True)

In [ ]:
df.isnull().sum()

Package Name                     0
Package Type                     0
Destination                      0
Itinerary                        0
Places Covered                   0
Travel Date                      0
Hotel Details                 4167
Start City                       0
Airline                          0
Per Person Price                 0
Sightseeing Places Covered       0
Cancellation Rules               0
dtype: int64

In [ ]:
df.columns.tolist()

['Package Name',
 'Package Type',
 'Destination',
 'Itinerary',
 'Places Covered',
 'Travel Date',
 'Hotel Details',
 'Start City',
 'Airline',
 'Per Person Price',
 'Sightseeing Places Covered',
 'Cancellation Rules']

In [ ]:
df.duplicated().sum()

np.int64(12)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df["Package Type"].value_counts().tail(20)

#Counts how many times each value appears in the Package Type column.
#Show me the 20 least frequent Package Type values so I can inspect the suspicious ones.

Package Type
https://holidayz.makemytrip.com/holidays/india/package?id=35114&depCityId=1268&listingClassId=84&depDateMilliSec=1571443200000      1
https://holidayz.makemytrip.com/holidays/india/package?id=26197&depCityId=1218&listingClassId=10&depDateMilliSec=1571270400000      1
https://holidayz.makemytrip.com/holidays/india/package?id=41677&depCityId=1268&listingClassId=2519&depDateMilliSec=1571875200000    1
https://holidayz.makemytrip.com/holidays/india/package?id=33473&depCityId=1268&listingClassId=2519&depDateMilliSec=1570147200000    1
https://holidayz.makemytrip.com/holidays/india/package?id=31005&depCityId=1268&listingClassId=264&depDateMilliSec=1569801600000     1
https://holidayz.makemytrip.com/holidays/india/package?id=36607&depCityId=1218&listingClassId=2519&depDateMilliSec=1571961600000    1
https://holidayz.makemytrip.com/holidays/india/package?id=34370&depCityId=1268&listingClassId=12&depDateMilliSec=1569974400000      1
https://holidayz.makemytrip.com/holidays/india/package?id=32441&depCityId=1218&listingClassId=2519&depDateMilliSec=1570924800000    1
https://holidayz.makemytrip.com/holidays/india/package?id=26311&depCityId=1268&listingClassId=84&depDateMilliSec=1571097600000      1
https://holidayz.makemytrip.com/holidays/india/package?id=33969&depCityId=1268&listingClassId=12&depDateMilliSec=1570320000000      1
https://holidayz.makemytrip.com/holidays/india/package?id=33803&depCityId=1268&listingClassId=2519&depDateMilliSec=1569888000000    1
https://holidayz.makemytrip.com/holidays/india/package?id=37341&depCityId=1218&listingClassId=2519&depDateMilliSec=1569715200000    1
https://holidayz.makemytrip.com/holidays/india/package?id=25935&depCityId=1268&listingClassId=12&depDateMilliSec=1571356800000      1
https://holidayz.makemytrip.com/holidays/india/package?id=35112&depCityId=1268&listingClassId=84&depDateMilliSec=1570924800000      1
https://holidayz.makemytrip.com/holidays/india/package?id=30601&depCityId=1268&listingClassId=606&depDateMilliSec=1570233600000     1
https://holidayz.makemytrip.com/holidays/india/package?id=41405&depCityId=1218&listingClassId=84&depDateMilliSec=1570406400000      1
https://holidayz.makemytrip.com/holidays/india/package?id=33215&depCityId=1218&listingClassId=303&depDateMilliSec=1571702400000     1
https://holidayz.makemytrip.com/holidays/india/package?id=29181&depCityId=1268&listingClassId=10&depDateMilliSec=1571443200000      1
https://holidayz.makemytrip.com/holidays/india/package?id=30303&depCityId=1268&listingClassId=303&depDateMilliSec=1572048000000     1
https://holidayz.makemytrip.com/holidays/india/package?id=28071&depCityId=1268&listingClassId=8&depDateMilliSec=1570665600000       1
Name: count, dtype: int64

In [ ]:
#This code checks every value in the Package Type column and keeps only the five valid categories: 
# Budget, Standard, Deluxe, Premium, and Luxury. The ~ means "not", so it identifies values that 
# are not in that list, and df.loc[...] selects those rows. 
# Finally, = np.nan replaces those invalid URL-like values with missing values (NaN) 
# instead of deleting the entire rows, allowing us to handle them later during preprocessing.


df.loc[
    ~df["Package Type"].isin(
        ["Budget", "Standard", "Deluxe", "Premium", "Luxury"]
    ),
    "Package Type"
] = np.nan

In [ ]:
#counts how many times each value appears in the Package Type column.
#By default, value_counts() doesn't show missing (NaN) values. 
# Setting dropna=False tells pandas to include them in the count, so we can see how many rows have missing values in the Package Type column after our cleaning step.

df["Package Type"].value_counts(dropna=False)

Package Type
Deluxe      7434
Standard    7194
Premium     7023
Luxury      4065
NaN         1087
Budget       639
Name: count, dtype: int64

In [ ]:
df["Package Type"] = df["Package Type"].fillna(
    df["Package Type"].mode()[0]
)

In [ ]:
df["Package Type"].isnull().sum()

np.int64(0)

In [ ]:
#Now we will handle the outliers in price per person column.
#As we checked earlier it was skewed by 2.57 

df["Per Person Price"].skew()

np.float64(2.571992723354743)

In [ ]:
Q1 = df["Per Person Price"].quantile(0.25)
Q3 = df["Per Person Price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower:", lower)
print("Upper:", upper)

Lower: -6311.125
Upper: 43263.875

In [ ]:
#This is legit packages with price per person greater than upper limit.
#Hence useful

df[df["Per Person Price"] > upper].shape[0]

981

In [ ]:
df.shape

(27442, 12)

In [ ]:
df.to_csv(
    r"E:\MLOps\MMT\Data\Cleaned\MMT_Cleaned.csv",
    index=False
)